#pragma once

#define FPS_LIMIT 60
#define FRAME_TIME (1.0 / FPS_LIMIT)

#define INPUT_ARROW_UP ((char)193)
#define INPUT_ARROW_DOWN ((char)194)
#define INPUT_ARROW_LEFT ((char)180)
#define INPUT_ARROW_RIGHT ((char)195)

#define INPUT_DIRECTION_UP 'w'
#define INPUT_DIRECTION_LEFT 'a'
#define INPUT_DIRECTION_DOWN 's'
#define INPUT_DIRECTION_RIGHT 'd'


// #define DEBUG
#define _DEFAULT_WINDOW_HEIGHT 30
#define _DEFAULT_WINDOW_WIDTH 120
#ifdef DEBUG
#define DEBUG_INFO_LINES 1
#define DEFAULT_WINDOW_HEIGHT (_DEFAULT_WINDOW_HEIGHT-DEBUG_INFO_LINES)
#else
#define DEFAULT_WINDOW_HEIGHT (_DEFAULT_WINDOW_HEIGHT)
#endif
#define DEFAULT_WINDOW_EXTRA_WIDTH 1 // utilizzato per caratteri speciali quali \n, \0,...
#define DEFAULT_WINDOW_WIDTH (_DEFAULT_WINDOW_WIDTH - DEFAULT_WINDOW_EXTRA_WIDTH)

#define DEFAULT_VIEWPORT_HEIGHT (DEFAULT_WINDOW_HEIGHT*2)
#define DEFAULT_VIEWPORT_WIDTH (DEFAULT_WINDOW_WIDTH)
